services:
  mysql:
    image: mysql:9.5.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "localhost"
      MYSQL_DATABASE: library_system
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - library_data:/var/lib/mysql
volumes:
  library_data:
